colors:
  # Default colors
  primary:
    background: '#303030'
    foreground: '#d0d0d0'
  # Normal colors
  normal:
    black:   '#151515'
    red:     '#ac4142'
    green:   '#90a959'
    yellow:  '#f4bf75'
    blue:    '#6a9fb5'
    magenta: '#aa759f'
    cyan:    '#75b5aa'
    white:   '#d0d0d0'
  # Bright colors
  bright:
    black:   '#505050'
    red:     '#ac4142'
    green:   '#90a959'
    yellow:  '#f4bf75'
    blue:    '#6a9fb5'
    magenta: '#aa759f'
    cyan:    '#75b5aa'
    white:   '#f5f5f5'
